# Generated by Django 4.2.4 on 2023-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('current_rate_api', models.CharField()),
                ('last_24_hours_api', models.CharField()),
            ],
        ),
    ]
