# Generated by Django 4.2.4 on 2023-08-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('active', models.BooleanField(default=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location_app.location')),
            ],
        ),
    ]
