# Generated by Django 4.2.4 on 2023-08-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
        ('equipment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipments', to='location_app.location'),
        ),
    ]
