# Generated by Django 4.2.4 on 2023-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0002_alter_equipment_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(),
        ),
    ]
