# Generated by Django 4.2.4 on 2023-08-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0003_alter_equipment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='active',
        ),
    ]
