# Generated by Django 4.2.4 on 2023-08-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_alter_location_provider_id_alter_location_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='active',
        ),
    ]
