# Generated by Django 4.2.4 on 2023-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(),
        ),
    ]
